# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Test F3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test F3
  pod 'MercadoPagoSDK', '2.2.4'


  target 'Test F3Tests' do
    inherit! :search_paths
    # Pods for testing
  pod 'MercadoPagoSDK', '2.2.4'

  end

  target 'Test F3UITests' do
    inherit! :search_paths
    # Pods for testing
  pod 'MercadoPagoSDK', '2.2.4'

  end

end
